### ISSUE TITLE
Any plans to make this Dart 2 compatible?

### ISSUE THREAD

**Issue by martflu** [Jaguar-dart/stencil#1]

**Comment by tejainece** [comment]
Do you mean Dart2.0.0 stable?

**Comment by martflu** [comment]
Yes. We are using `stencil` and are currently trying to switch to 2.0.0.

**Comment by tejainece** [comment]
Ok. Fixing it.

**Comment by tejainece** [comment]
Released `stencil`: `2.1.6` that supports Dart 2 stable.
